name: Test

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: sudo apt-get install libgif-dev
    - name: make
      run: make
    - name: make test
      run: make test
